# Generated by Django 5.0.7 on 2026-09-04 21:37

import cards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('attributes', cards.models.JSONField(default=list, help_text='List of attributes with name and type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buff',
                'verbose_name_plural': 'Buffs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('attributes', cards.models.JSONField(default=list, help_text='List of attributes with name and type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Effect',
                'verbose_name_plural': 'Effects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(help_text="URL of the card's image")),
                ('level', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('races', models.ManyToManyField(blank=True, help_text='Races assigned to this card', related_name='cards', to='cards.race')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardAppliedBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', cards.models.JSONField(default=dict, help_text='Specific parameters for this buff on this card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.buff')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_buffs', to='cards.card')),
            ],
            options={
                'verbose_name': 'Applied Buff',
                'verbose_name_plural': 'Applied Buffs',
                'unique_together': {('card', 'buff')},
            },
        ),
        migrations.CreateModel(
            name='CardContainedEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', cards.models.JSONField(default=dict, help_text='Specific parameters for this effect on this card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='cards.card')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.effect')),
            ],
            options={
                'verbose_name': 'Contained Effect',
                'verbose_name_plural': 'Contained Effects',
                'unique_together': {('card', 'effect')},
            },
        ),
    ]
