# Generated by Django 5.0.7 on 2026-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image file (stored and served by Django)', null=True, upload_to='cards/'),
        ),
    ]
