# Generated by Django 5.0.7 on 2026-09-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collections this card belongs to', related_name='cards', to='cards.collection'),
        ),
    ]
